CREATE TABLE IF NOT EXISTS image (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL ,
    url TEXT UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS tag (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS image_tag (
    image_id INTEGER NOT NULL ,
    tag_id INTEGER NOT NULL ,UNIQUE (image_id, tag_id)
);
