name: Auto release

on:
  push:
    tags: 
      - 'v*'
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'

jobs:
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Run the Gradle bootJar
      uses: gradle/gradle-build-action@v2
      with:
        arguments: bootJar
    - name: Check Tag Push
      run: echo "tag=${REF##*/v}" >> $GITHUB_ENV
    
    - name: Check Tag workflow dispatch
      if: github.event_name == 'workflow_dispatch'
      run: echo "tag=test" >> $GITHUB_ENV
    
    - name: Create release
      uses: softprops/action-gh-release@v0.1.4
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: $${{ env.tag }}
        draft: false
        files: build/libs/*
