name: Docker Image CI

on:
  push:
    branches: 
     - master
    tags:
    - 'v*'
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Check tag
      if: startsWith(github.ref, 'refs/tags/v')
      run: echo "TAG=${GITHUB_REF##*/v}" >> $GITHUB_ENV
       
       
#     - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag imagesearch:$TAG
      
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: usbharu/imagesearch
        tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
